apiVersion: apps/v1
kind: Deployment
metadata:
  name: prime-clone
  namespace: default
  labels:
    app: prime-clone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prime-clone
  template:
    metadata:
      labels:
        app: prime-clone
    spec:
      containers:
      - name: prime-clone
        image: 567017110325.dkr.ecr.us-east-1.amazonaws.com/prime-clone:12
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "256Mi"
            cpu: "200m"
          requests:
            memory: "128Mi"
            cpu: "100m"
