apiVersion: apps/v1
kind: Deployment
metadata:
  name: prime-clone
  labels:
    app: prime-clone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prime-clone
  template:
    metadata:
      labels:
        app: prime-clone
    spec:
      containers:
      - name: prime-clone
        image: 567017110325.dkr.ecr.us-east-1.amazonaws.com/prime-clone:17
        ports:
        - containerPort: 80
